{
    'name': 'Havano ERP (havanoposdesk_odoo)',
    'version': '19.0.1.2',
    'category': 'Sales/Point of Sale',
    'summary': 'Unified ERP backend serving Flutter POS app and Odoo UI',
    'description': """
        Havano ERP Odoo App.
        Manages Inventory, Products, Sales, Suppliers, and multi-tenancy.
        Provides JSON REST API for the Flutter Havano POS frontend.
    """,
    'author': 'Havano',
    'depends': ['base', 'web', 'base_setup', 'auth_signup', 'payment', 'havano_payments', 'mail', 'spreadsheet_dashboard', 'utm'],
    'data': [
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        'security/access_rights.xml',
        'core/views/hide_menus.xml',
        'core/data/cron.xml',
        'core/data/whitelabel_data.xml',
        'inventory/data/sequence.xml',
        'core/views/store_views.xml',
        'core/views/res_users_views.xml',
        'core/views/user_rights_views.xml',
        'core/views/saas_users_views.xml',
        'core/views/subscription_views.xml',
        'core/views/terminal_views.xml',
        'core/views/tenant_views.xml',
        'core/views/res_config_settings_views.xml',
        'core/views/tenant_admin_views.xml',
        'core/views/whitelabel_templates.xml',
        'core/views/error_log_views.xml',

        'accounts/views/account_views.xml',
        'accounts/views/expense_views.xml',
        'accounts/views/tax_views.xml',
        'accounts/views/payment_views.xml',
        'accounts/data/tax_data.xml',
        'core/views/menus.xml',
        'inventory/views/category_views.xml',
        'inventory/views/uom_views.xml',
        'inventory/views/pricelist_views.xml',
        'inventory/views/product_views.xml',
        'inventory/views/stock_adjustment_views.xml',
        'inventory/views/report_views.xml',
        'suppliers/data/sequence.xml',
        'suppliers/wizard/purchase_return_wizard_views.xml',
        'suppliers/views/purchase_views.xml',
        'suppliers/views/supplier_views.xml',
        'sales/data/sequence.xml',
        'sales/wizard/sale_return_wizard_views.xml',
        'sales/views/sale_views.xml',
        'sales/views/customer_views.xml',
        'sales/views/item_profitability_report_views.xml',
        'sales/views/category_sales_report_views.xml',
        'sales/views/cashier_sales_report_views.xml',
        'sales/views/terminal_sales_report_views.xml',
        'sales/views/daily_sales_report_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_migrate',
    'assets': {
        'web.assets_backend': [
            'Havanoposdesk_odoo/static/src/js/user_menu_hide.js',
            'Havanoposdesk_odoo/static/src/js/whitelabel.js',
        ],
    },
}
