from . import tenant
from . import res_users
from . import store
from . import terminal
from . import subscription
from . import payment
from . import payment_transaction
from . import res_config_settings
from . import res_currency_rate
from . import user_rights
from . import ir_module_module
from . import ir_http
from . import error_log
from . import dashboard
from . import support_ticket
from . import ir_actions_act_window 